### ISSUE TITLE
CPSV:FormalFramework versus OSLO:JuridischKader

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#10]
OSLO1 heeft als concept een `JuridischKader`, terwijl ISA een `FormalFramework` refereert.

Definitie JuridischKader (uit [OSLO1.1 spec 2.6.3](https://www.v-ict-or.be/assets/5384d510ce3fb57c500006ad/OSLO1.1-specificaties.pdf))

> De machtigingen zijn afgeleid van het juridisch kader, i.e. een set van wetten, decreten en
> richtlijnen die een bepaalde dienstverlening of machtiging documenteren.
> Het juridisch kader dat hier bedoeld wordt, is specifiek in het kader van de machtigingen die
> gebruikt worden om rollen te typeren in het kader van een bepaalde dienstverlening.

Definitie FormalFramework (uit [ISA core](https://joinup.ec.europa.eu/asset/core_vocabularies/asset_release/core-vocabularies-v11#download))

> Legislation, policy, or policies lying behind the rules that govern a public service.

Beschrijving FormalFramework

> Instances of the Formal Framwork class are FRBR Expressions, i.e., concrete expressions of the more abstract concept of the piece of legislation or policy itself.
> 
> The European Council's invitation to introduce the European Legislation Identifier and portals such as legislation.gov.uk are relevant in this context. Adding '/data.xml' or /data.rdf' to any legislation URI on legislation.gov.uk will reveal how this can be done, for example http://www.legislation.gov.uk/uksi/2012/3170/contents/made{/data.rdf or /data.xml}.

Zijn deze concepten equivalent of niet? Er zijn voorbeelden nodig.

**Comment by dhaeneth** [comment]
Binnen OSLO worden zowel Agent, Dienstverlening en Juridisch Kader in één logisch geheel gebruikt, terwijl dit niet zo is/hoeft te zijn. Je hebt het 'Juridisch Kader' zowel binnen Dienstverlening, Organisatie (maar ook evenzeer Persoon of andere concepten). 

Het Juridisch Kader moet je bijna op zichzelf zien, waarbij instanties ervan verwijzen naar telkens andere kernconcepten (de voorbeelden zullen dus ook verschillen per kernconcept).

Ze zijn dus equivalent op een rudimentair niveau.

**Comment by GeertThijs** [comment]
@dhaeneth: JuridischKader is een onafhankelijke entiteit in OSLO en ook in de refactored CPSV, CPSV-AP en CPOV en kan dus herbruikt worden en wordt ook herbruikt. Hier gaat het gewoon dat FormalFramework een breder begrip lijkt dan JuridischKader. Iets kan formeel worden afgesproken maar is daarom niet juridisch vastgelegd.

**Comment by GeertThijs** [comment]
@rafbuyle: Kan jij eventueel een voorbeeld geven van een FormeelKader dat buiten de wet staat?

**Comment by DieterDePaepe** [comment]
Deze discussie wordt verdergezet in de publieke discussie groep.
