### ISSUE TITLE
Verhouding OSLO:Agent en ISA:Agent

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#11]
In [OSLO1.1](https://www.v-ict-or.be/assets/5384d510ce3fb57c500006ad/OSLO1.1-specificaties.pdf) is een Agent gedefinieerd als volgt:

Sectie 2.4.1

> Agent is een supertype van PERSOON, ORGANISATIE en HOEDANIGHEID. Een agent is een
> entiteit die een rol kan aannemen in dienstverlening.
> De aanleiding van dit concept is om er enerzijds voor te zorgen dat er een ontkoppeling is tussen
> het domein ‘contactinformatie’ en ‘dienstverlening’ die zorgt voor meer stabiliteit van de
> standaard. De agent laat toe om in het domein dienstverlening abstractie te nemen van de
> entiteiten persoon, organisatie en hoedanigheid.
> Toekomstgericht is dit een goede praktijk daar dit toelaat om andere ‘agents’ in te voeren zonder
> impact op het schema van de dienstverlening. Een mogelijk voorbeeld is het invoeren van een
> ‘authentieke service’ die kan optreden als behandelaar in een dossier (algoritme).

Sectie 2.6.6

> Een persoon of organisatie kan al dan niet onder een bepaalde hoedanigheid, zij het privé of in
> naam van een organisatie, een bepaalde rol aannemen bij een bepaalde dienstverlening. Dit
> geeft aanleiding tot bijkomende relaties die betrekking hebben op Dienstverlening. Agent is dus
> geen tussenentiteit maar een abstractie en wordt zelf nooit gebruikt in de beschrijving. Enkel de
> instanties zelf worden gebruikt: Persoon hoedanigheid en Organisatie.

[ISA Agent](http://joinup.ec.europa.eu/site/core_vocabularies/Core_Vocabularies_v1.1/Core_Vocabularies_v1.1.htm) heeft volgende definitie (ISA herbruikt in feite [foaf:Agent](http://xmlns.com/foaf/spec/#term_Agent)):

> An entity that is able to carry out actions.

Wat is de precieze verhouding tussen deze 2 agents en hun subklassen? Is een Organisatie gelijk aan een RegisteredOrganisation? Is een Group gelijk aan een FeitelijkeOrganisation?

**Comment by dhaeneth** [comment]
OSLO:Agent is zoals je zelf zegt de superklasse van organisatie, hoedanigheid of persoon (of andere bij uitbreiding).  

Zoals ik het zie, moet je OSLO:Organisatie gelijk kunnen stellen aan foaf:Organization. Foaf is mij echter nog te beperkend. 
Je moet OSLO:Organisatie evenzeer zien als een subklasse van org:Organization, niet disjoint tot org:FormalOrganization of rov:Organization (een subklasse van org:FormalOrganization).

**Comment by GeertThijs** [comment]
@dhaeneth: Afgaand op de properties mapt OSLO:Organisation tegelijk op ORG:Organisation en op diens subklasse REGORG:RegisteredOrganisation. Ik zou de subtyping van ORG, REGORG en ook CPOV overnemen, allemaal niet disjoint. Zie figuur hieronder. ORG gebruikt niet de Organisation van FOAF maar heeft er zelf één bedacht. 
![orgregorgcpov](https://cloud.githubusercontent.com/assets/22620291/19857178/0892c5d6-9f7d-11e6-9219-89b1b98a08c1.png)

**Comment by GeertThijs** [comment]
Nu wat de issue zelf beteft:

- OSLO werkt de subklassen Persoon, Organisatie, Hoedanigheid uit
- ORG heeft het over Organisation & Person (onderling disjoint) en Group

Vragen die ik daarbij heb:

- Doen wij ook iets met Group?
- Is er ergens een bestaand vocabularium voor Hoedanigheid? Of nemen we wat we al hadden voor OSLO?
- Wat is er disjoint? In ORG wordt gesteld dat een Person niet tegelijk een Organisation kan zijn en omgekeerd. Maar een Person kan wel ook een Group zijn (met slechts 1 lid)? Een Organisation kan je ook als Group bekijken. En voor OSLO: zijn Persoon en Organisatie daar ook disjoint? En Hoedanigheid?

**Comment by DieterDePaepe** [comment]
Foaf:Agent

> An agent (eg. person, group, software or physical artifact). 
> The Agent class is the class of agents; things that do stuff

Foaf:Organisation of Org:Organization (Gedefinieerd als [equivalent](https://www.w3.org/TR/vocab-org/#class-organization))

> Foaf definitie:
> The Organization class represents a kind of Agent corresponding to social instititutions such as companies, societies etc.
> This is a more 'solid' class than Group, which allows for more ad-hoc collections of individuals. These terms, like the corresponding natural language concepts, have some overlap, but different emphasis.
>
> Org definitie:
> Represents a collection of people organized together into a community or other social, commercial or political structure. The group has some common purpose or reason for existence which goes beyond the set of people belonging to it and can act as an Agent. Organizations are often decomposable into hierarchical structures.

Foaf:Group
> The Group class represents a collection of individual agents (and may itself play the role of a Agent, ie. something that can perform actions).
> This concept is intentionally quite broad, covering informal and ad-hoc groups, long-lived communities, organizational groups within a workplace, etc. Some such groups may have associated characteristics which could be captured in RDF (perhaps a homepage, name, mailing list etc.).

Group en Organization hangen vrij dicht bij elkaar. Ik vermoed echter dat we met Organization alles voor OSLO gaan kunnen modelleren.

Voor Hoedanigheid vind ik dat we eigenlijk Foaf:Person kunnen herbruiken.

> The Person class represents people. Something is a Person if it is a person. We don't nitpic about whether they're alive, dead, real, or imaginary. The Person class is a sub-class of the Agent class, since all people are considered 'agents' in FOAF.

**Comment by DieterDePaepe** [comment]
Zie [deze comment](https://github.com/Informatievlaanderen/OSLO/issues/28#issuecomment-260633621) voor mogelijks bewijs dat `Agent` algemeen als hoedanigheid kan gebruikt worden.

**Comment by GeertThijs** [comment]
Ik zie het verband niet met Hoedanigheid. Hoedanigheid zegt welke functie een persoon uitoefent (meestal maar niet altijd bij een organisatie, het kan ook gewoon een beroep zijn of zo). Evenmin abstract te benaderen, het is een specifieke persoon die werkt bij een specifieke organisatie.

**Comment by DieterDePaepe** [comment]
Heb een apart issue gemaakt voor hoe `Agent` mag gebruikt worden (als een `foaf:Person` een categorie zou mogen voorstellen, zou het ook kunnen een hoedanigheid voorstellen, anders wellicht niet) #38

**Comment by DieterDePaepe** [comment]
Het resultaat van de interne (voorafgaande) werkgroepen heeft `foaf:Agent` geadopteerd.
