### ISSUE TITLE
Hoort OSLO1:Product:geldigheidsperiode bij CPSV:Output?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#13]
Deze issue gaat er van uit dat OSLO1 Product als het resultaat van een dienst ziet (bvb een paspoort). Is het de bedoeling dat er een geldigheidsperiode wordt bijgehouden hiervan?

**Comment by DieterDePaepe** [comment]
De [OSLO1 spec](https://www.v-ict-or.be/assets/5384d510ce3fb57c500006ad/OSLO1.1-specificaties.pdf) mapt in sectie 3.4.1 `OSLO1:Product` op `CPSV:Output`. Dit bevestigd dat het de bedoeling was om geldigheid op output bij te houden.

**Comment by dhaeneth** [comment]
Inderdaad. Een product zoals hier gezien vormt een object op zich met een levenscycles.

**Comment by GeertThijs** [comment]
In de OSLO specs is sprake van Geldigheidsduur (hoe lang is het product bv een vergunning geldig), maar in het diagram is dat Geldigheidsperiode geworden (bedoeld als ValidTime, ttz het moment of de periode waarvoor het gegeven geldig is in de realiteit).

**Comment by DieterDePaepe** [comment]
Er is een groot verschil tussen een duur (1 maand) tegenover een periode (van 1 januari 2016 tot 1 februari 2016). Het eerste kan volgens mij relevant zijn in sommige cases:

> De vergunning is 1 maand geldig.

Het tweede niet, aangezien het elke dag zou moeten geupdate worden.

> De vergunning (indien vandaag aangevraagd) is geldig van "datum vandaag" tot "datum vandaag + 1 maand"

Uit de oslo definitie is me niet duidelijk om welke het gaat. Zijn jullie akkoord dat het hier om het eerste gaat?

**Comment by dhaeneth** [comment]
Het gaat hier (Oslo:Geldigheidsduur) om de geldigheidsduur van een dienstverlening (met bijhorend product). Ook afh. van use case. 

Beschouwen we de cataloog (IPDC). Een DV kent een begin en een eind. Dat kan recurrent (voor een bepaalde datum elk jaar) of absoluut (1/1/2017 - ...). Wat jij aanhaalt, is de geldigheidsduur van een individueel product (is iets anders). Hoort volgens de logica van CPSV-AP dacht ik thuis onder de Rules van de dienstverlening (vergunning is x maand geldig).

**Comment by DieterDePaepe** [comment]
@dhaeneth Ik volg niet volledig. De OSLO spec heeft meerdere voorkomens van `Geldigheidsduur`, ik ga er van uit dat het gaat om het attribuut gedefinieerd op `OSLO:Product`. Nu, `OSLO:Product` wordt gemapt op `CPSV:Output` volgens #2. Dus moet het gaan over de geldigheid van een resultaat van een dienstverlening volgens mij, zoals bijvoorbeeld de geldigheid van een paspoort of licentie.

Bij `OSLO:DienstVerlening` zie ik geen geldigheid. Los daarvan, voor het bepalen wanneer een dienstverlening algmeen beschikbaar is, is er het `temporal` attribuut op `PublicService`.

**Comment by dhaeneth** [comment]
@dieterdepaepe Voor de bepaling van de algemene geldigheid (lifecycle of fase daarin) van Dienstverlening hebben we dat in elk geval wel nodig en is in OSLO nog niet voorzien. Daarin beperken we ons vandaag --> dat moet verruimen.

OSLO:Product mapt idd op CPSV-(AP):Output. In die zin wijken we af van CPSV door de Geldigheidsduur als attribuut van Product te stellen ipv. als Rule voor een Dienstverlening van een Product. Dat concept is vandaag niet voorzien in OSLO, maar hebben we wel nodig. Het slaat de brug tussen Dienstverlening en JuridischKader. De ambitie moet zijn om dit mee te nemen (er is nood aan; denk ik maar aan IPDC, SlimmeSubsidies, Burgerloket), maar betekent een change tav. OSLO1. Dit heeft ook te maken met het feit dat we in onze specs geïnstantieerde producten ondersteunen ('mijn' product) waar dit in CPSV niet is. OSLO1 had vnl. die case voor ogen en dat botst...
--> mbt je vraag : als we het hebben over de algemene geldigheid van een product (zoals reglementair vastgelegd - dus één maand geldig bvb.) zou ik streven dit op te nemen als Regel (Rule). Dat zou afwijken van OSLO1.
Rest de vraag of we Product:Geldigheidsperiode wel willen opnemen in het model (dus: willen we een antwoord bieden aan de wereld van Dosis, ondernemersloket, burgerloket, ...)? Dit is een UC die CPSV(-AP) niet ondersteunt vandaag. Die vragen worden gesteld en dat komt er mi vroeg of laat wel aan.
In die zin lijkt het me absoluut relevant. Het is een periode (dus van...tot) en wordt denk ik best gebruikt enkel in die gevallen waarin een individuele dienstverlening beschreven is (dosis edm.).

**Comment by DieterDePaepe** [comment]
> Voor de bepaling van de algemene geldigheid (lifecycle of fase daarin) van Dienstverlening hebben we dat in elk geval wel nodig en is in OSLO nog niet voorzien. Daarin beperken we ons vandaag --> dat moet verruimen.

Ik ben niet volledig vertrouwd met de levenscycli dat diensten doorlopen. Gaat het hier bvb om: "Actief", "Gepland" (dienst die binnenkort beschikbaar zal zijn), "Stopgezet"?

Ik ben ook voorstander om `Rule` te gebruiken voor bvb geldigheid. (Ik ben zelf niet zeker of het daarin past, maar dat is eerder omdat ik nog wat voeling mis rond `Rule` en `FormalFramework`. Wel direct een bedenking: kan een geldigheidsperiode die in een `Rule` zit geïnterpreteerd worden door een machine?

`OSLO:geldigheidsPeriode` zoals gedefinieerd op `OSLO:Product` hoort niet thuis in onze huidige scope lijkt mij. Hoewel `CPSV:Output` en `OSLO:Product` op elkaar mappen stelt het eerste iets abstract voor en het tweede iets concreet (een instantie).

**Comment by GeertThijs** [comment]
- Geldigheidsperiode slaat op de periode waarin een object bestaat in de realiteit. Voor een Dienstverlening betekent dit de periode dat de Dienstverlening bestaat of heeft bestaan en voor een Output idem.
- Geldigheidsduur is eigenlijk iets anders, het geeft aan hoe lang een Output (bv paspoort) geldig is. Concreet kan een paspoort 5 jaar geldig zijn maar bv na 3 jaar toch om één of andere reden worden vernietigd. Probleem is dat in OSLO bij de specs Geldigheidsduur staat maar in het diagram per ongeluk Geldigheidsperiode.
- Rule lijkt geschikt voor geldigheidsduur maar niet voor geldigheidsperiode. Echter is dit de definitie van Rule: The Rule class represents a document that sets out the specific rules, guidelines or procedures that the Public Service follows. It includes the terms of service, licence, and authentication requirements of the Public Service. Ik zou het vertalen als Reglement (passend binnen een bepaalde wetgeving). Geldigheidsduur van bv een paspoort zal daar zeker instaan, maar begraven tussen alle andere aspecten vh reglement. Maar misschien is dat voldoende, anders zouden we veel properties nodig hebben om een product volledig beschreven te kunnen hebben.
- Blijkt dus wel dat het woordje geldigheid verwarrend is in Geldigheidsperiode. Het officiële engelstalige equivalent in de wereld van lifecycleinfo is ValidTime (versus SystemTime), vandaar de naam. Wie weet een betere naam?
- Of we nu al aan de slag gaan met historiek kaart ik aan in issue #32.

**Comment by DieterDePaepe** [comment]
Geldigheidsperiode voor een `PublicService` wordt volledig gecoverd door het `temporal` attribuut.

**Comment by GeertThijs** [comment]
Staat in de specs als volgt:

> 3.12.2.	Start date and end date [0..1]
The start data and end date properties represents the start and end of the period that the Public Service is available or active. 
There is a degree of flexibility in the way they are used. If the value is a complete date then that indicates a specific date and should by typed using the well-known xsd:date which is conformant to ISO8601. However, if a service is only available for certain periods of the year then the values can be numeric representations of the month (the MM part of an ISO8601 date) typed as xsd:gMonth. For example, to state that a public service is available between April and September the value of startDate would be 04 and endDate 09. 
A start date may be given without an end date, indicating that the public service/channel is ongoing.

Maw: niet enkel de klassieke validtime (gedigheidsperiode vh gegeven op het terrein). Maar ook een soort openingsuren of eerder: openingsmaanden.

Ik voegde deze comment nog toe op [joinup](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/opening-hours-does-not-belong-period-time#comment-19047).

**Comment by DieterDePaepe** [comment]
Uit de ISA virtual meeting van 2016-11-18 is gebleken dat er geen consensus bestond over de betekenis/nood van `temporal` tegenover de openingsuren. Het `temporal` attribuut was NIET bedoeld om life cycle informatie bij te houden, maar eerder bijvoorbeeld seizoenale beschikbaarheid.

**Comment by DieterDePaepe** [comment]
Discussie wordt verderzet in de publieke discussie groep: https://github.com/Informatievlaanderen/OSLO-Public-Discussion/issues/12
