### ISSUE TITLE
CPSV-AP: Public Organisation has 2 identifiers

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#14]
`CPSV-AP:PublicOrganisation` has 2 identifiers by deriving from `CPSV:Agent`. As these are probably meant as RDF URI identifiers this poses no real problem, but conceptually this is confusing.

**Comment by dhaeneth** [comment]
OK - logisch gezien vormt een Publ. Org. natuurlijk een specificatie van een Agent. De 'generalisatie-pijl' in het model kent in CPSV-AP een andere invulling. Best melden aan ISA.

**Comment by GeertThijs** [comment]
Er zijn zo nog gevallen van dubbele elementen (zie ook #33) welke oplossen van zodra in de specs gezegd wordt dat de ene versie gebonden is aan de andere. Zo is CPOV:Identifier gebonden aan ORG:Identifier en kon ik deze weglaten uit het Organisatie-model (zie org_withCpovAndRovAndOSLO).

**Comment by DieterDePaepe** [comment]
[Link naar Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/public-organisation-has-2-identifiers)

**Comment by GeertThijs** [comment]
Merci Dieter voor de extra uitleg bij deze issue op joinup. Goede voorbereiding voor de webinar vrijdag.

**Comment by DieterDePaepe** [comment]
Dit issue is gecorrigeerd aan de kant van ISA na onze feedback.
