### ISSUE TITLE
CPSV-AP: Participation overlapt met uses/provides

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#17]
CPSV-AP definieert naar de relaties `uses` en `provides` een extra entiteit `Participation` tussen Agent en PublicService. Deze entiteit overlapt eigenlijk in functie.

Voorgestelde oplossing: `uses` en `provides` opnemen in `Participation`.

**Comment by dhaeneth** [comment]
Het zijn wel andere relaties. In RDF-opzicht zijn de predicaten anders. Uses is een afzonderlijke relatie 'Agent maakt gebruik van' (dus zondermeer), terwijl de participation meer ingaat op de rol die de agent speelt in de dienstverlening. De rol is een verplichting - dit samen nemen zou betekenen dat je verplicht bent om de rol te definiëren van 'gebruiker' in de relatie 'uses'. Lijkt wat bij het haar gegrepen...

**Comment by GeertThijs** [comment]
@dhaeneth: Neenee, je zou verplicht zijn om de Rol "Gebruiker" op te geven in de relatie HasParticipation. De relatie Uses zou als relatie niet meer bestaan.

**Comment by GeertThijs** [comment]
Voordeel van het behoud van Uses en Provides is het feit als je HasParticipation opgeeft dat je dan de verplichte Participation:Description moet invullen. En ook nog eens de rol (of rollen) moet kiezen uit een codelijst. Als iedereen het daartmee eens is kunnen we dit item beter sluiten.

**Comment by dhaeneth** [comment]
@GeertThijs wat stel je nu precies voor :-)? Uses opgeven in inbedden in 'Participation' is niet in tegenstrijd met CPSV-AP; we wijken er gewoon van af door de RDF-relaties in te bedden in Participation.

Ter info : de relatie uses : The uses property links an Agent to a Public Service in which it plays the specific role of user, meaning that it provides the input and receives the output but does not play any direct role in providing the service. This will typically be an individual citizen or an outside organisation.

**Comment by GeertThijs** [comment]
@dhaeneth: Je bedoelt: in tegenstrijd met CPSV. Nee inderdaad, we wijken er dan gewoon van af. Maar het feit dat je gewoon om een Uses of Provides relatie op te geven ook een Description zal moeten opgeven doet mij afhaken.

**Comment by DieterDePaepe** [comment]
Deze discussie wordt verdergezet in de publieke groep.

https://github.com/Informatievlaanderen/OSLO-Public-Discussion/issues/13
