### ISSUE TITLE
CPSV-AP: Event is actually EventType

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#18]
Isn't Event used in CPSVAP as an EventType? Purpose is to classify PublicService's according to the kind of LifefeEvent or BusinessEvent they appeal to. It is not the actual Life- or BusinessEvents (coupled to the lifecycle of a Person or Business) that is modeled here.

**Comment by dhaeneth** [comment]
Klopt. Het Event zelf wordt hier niet beschreven, maar het type Event. Vanuit de finaliteit van een vocabularium (referentie voor  implementaties) is dit ook logisch.

**Comment by GeertThijs** [comment]
@dhaeneth : Reden dus om de entiteit niet Event te noemen maar EventType?

**Comment by dhaeneth** [comment]
@GeertThijs eeuwige discussie tussen het object zelf, de data en de metadata :-).... nu, bij EventType ga ik automatisch denken aan een classificatie of een hiërarchie van events wat ook niet de bedoeling is... (is echt voer voor semantische specialisten ...). Gekaderd binnen de subklassen BusinessEvent en LifeEvent, maakt het de zaak nog wat complexer (dan moeten we ook spreken van BusinessEventType?)....

**Comment by DieterDePaepe** [comment]
[Link naar Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/event-actually-eventtype)

Ik volg Geert, gegeven dat Core Public Organisation gebruik maakt van ChangeEvent en FoundationEvent, waar deze dus wel instanties voorstellen.

**Comment by GeertThijs** [comment]
Idem: goede voorbereiding voor de webinar vrijdag.

**Comment by DieterDePaepe** [comment]
Deze discussie wordt voortgezet in https://github.com/Informatievlaanderen/OSLO-Public-Discussion/issues/14
