### ISSUE TITLE
CPSV-AP: is Event relevant buiten het applicatieprofiel?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#19]
Is er een nut voor CPSV-AP:Event buiten het applicatieprofiel (=buiten een service portal)?

**Comment by dhaeneth** [comment]
Volgens mij wel. Event omvat om. Business Event of Live Event. Business Event zal bvb. ook herbruikt worden binnen de implementatie van een organisatie- of bedrijfsregister. Life Event wordt idealiter herbruikt binnen de levenscyclus van Personen.

**Comment by GeertThijs** [comment]
Binnen CPOV en ORG komt enkel ChangeEvent voor...

**Comment by GeertThijs** [comment]
Dus die Events dienen vooral voor gebruikers die wel weten wat ze willen doen (bv een bedrijf opstarten of een job vinden) maar niet weten welke publieke dienstverlening hen daarbij kan helpen. Bv om een bedrijf op te starten moet je oa inschrijven in KBO, BTW-nummer activeren, beroepskennis bewijzen etc. Zie ook http://unpan1.un.org/intradoc/groups/public/documents/nispacee/unpan004382.pdf. Lijkt mij inderdaad ook relevant buiten de context ve service portal.

**Comment by DieterDePaepe** [comment]
Uit [discussies op Joinup](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/event-actually-eventtype) is gebleken dat in CPSV-AP met `Event` eigenlijk een type van events wordt bedoeld. Bij CPOV/ORG stellen de events specifieke instanties van events voor. Beiden verschillen dus.

**Comment by DieterDePaepe** [comment]
Event is mee opgenomen in het model dat gepresenteerd is aan de publieke werkgroepen.
