### ISSUE TITLE
Geschikte benaming voor OSLO1:Product

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#2]
In OSLO1 is Product in feite een Dienst of Goed, dit kan vooral gezien worden door het `toepassingsGebied` attribuut en de attributen van `OSLO1:DienstVerlening`.

Er is een geschikte benaming nodig voor deze entiteit.

**Comment by DriesBeheydt** [comment]
Tijdens werkgroep 2 Dienstverlening werd het voorstel geopperd om het product van een dienst 'output' te noemen.

**Comment by DieterDePaepe** [comment]
De [OSLO1 spec](https://www.v-ict-or.be/assets/5384d510ce3fb57c500006ad/OSLO1.1-specificaties.pdf) mapt in sectie 3.4.1 `OSLO1:Product` op `CPSV:Output` in plaats van `CPSV:PublicService`. Dit spreekt ons uitgangspunt tegen, of het gaat om een fout in de spec.

**Comment by DieterDePaepe** [comment]
Verdere opmerkingen uit werkgroep 2 Dienstverlening:

- Dienst wordt vaak verkeerd geïnterpreteerd (bvb: beschrijvingen als: wat doet een sportdienst).
- Lokale besturen vinden de term Dossier te plastisch, te veel documentgericht.
- Dienst kan gezien worden als de organisatorische eenheid van een organisatie.

**Comment by GeertThijs** [comment]
Zoals ik al zei in mijn commentaar bij #1: Laten we inderdaad maar gewoon OSLO:Product mappen op ISA:Output. Met bijbehorende reductie van Product (volgens Geraldine Goed & Dienst) tot de codelijst van Output in CPSVAP: Declaration, PhysicalObject, Code, FinancialObligation, FinancialBenfit, Recognition, Permit. Geen Dienstverlening als output dus, de Dienstverlening zelf wordt door ISA/PublicService beschreven. Voor te leggen aan Geraldine!

**Comment by GeertThijs** [comment]
@DieterDePaepe: Ivm "Dienst wordt vaak verkeerd geïnterpreteerd (bvb: beschrijvingen als: wat doet een sportdienst)". Om die reden is indertijd bij OSLO blijkbaar gekozen voor Dienstverlening, wat ook niet bijster goed klinkt. Zou het probleem niet vervallen als we over PubliekeDienst zouden spreken? Intussen is immers duidelijk dat we enkel publieke diensten gaan beschrijven (zie #3).

**Comment by DieterDePaepe** [comment]
Ter referentie, dit is de definitie van cpsv:Output:

> Outputs can by any resource - document, artefact - anything. In a specific context it is likely to be useful to either define a sub class or declare the particular resource to also be of another type as well. A general case might be a foaf:Document but where possible, it is better to refer to a controlled vocabulary of types. dcterms:type should be used to use to provide this information linking to a SKOS Concept.

+1 om Output te gebruiken.

@GeertThijs Het probleem vervalt inderdaad. (In feite, zolang we zelf geen termen definiëren, komt het probleem niet voor!)

**Comment by HenkV** [comment]
Ik vind dat er een duidelijk verschil is tussen een dienst en een product. Bij een dienst is er in principe altijd een interactie met een externe factor, een klant (kan intern of extern zijn) en bij een dienst vallen als het ware de consumptie en de productie samen. Een dienst kan leiden tot een product, maar het kan ook zijn dat er uiteindelijk geen product geleverd wordt (= geen resultaat). Ik vind het dan ook handig om van output te spreken (zoals bij CPSV), omdat men dit flexibel kan invullen. 
Bij een product gaat de productie in principe vooraf aan de consumptie. 
Public Service, als publieke dienstverlening, is zoals Geert al schreef, geen output, en volgen we beter de beschrijving van CPSV.

**Comment by DieterDePaepe** [comment]
De interne discussies lijken akkoord te zijn over het gebruik van `Output` als term.
