### ISSUE TITLE
CPSV-AP: Separate enumerations for Business and Life Event?

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#20]
The property Event:Type refers to a different codelist for each of its subclasses LifeEvent and BusinessEvent. So it probably would be better to move Type to the subclasses, so there would be a BusinessEvent:Type and a LifeEvent:Type each with its own codelist.

**Comment by GeertThijs** [comment]
Dit is eigenlijk een algemene modelleringsvraag. Eigenlijk hebben de subklassen BisinessEvent en LifeEvent hier eenzelfde property Type, maar de enumeratie die erachter zit is wel anders voor elke subklasse.

**Comment by DieterDePaepe** [comment]
[Link naar Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/separate-enumerations-business-and-life-event)

De huidige structuur is compatibel met het gebruik van verschillende codelijsten voor Business/Life-events. Het `Type` attribuut bevat een `Code`, waarbij je kan definiëren dat elke entry van een zelf gemaakte "BusinessLifeEventCodeList" een `Code` is.

**Comment by GeertThijs** [comment]
Kan je het bovenstaande wat toelichten, ik snap het niet. Ook Archer zijn antwoord versta ik niet. Mijn vraag is gewoon: hoe dwing je bij de gebruiker af dat hij voor een LifeEvent geen BusinessEventType invult als alles door elkaar in één codelijst staat?

**Comment by DieterDePaepe** [comment]
> De huidige structuur is compatibel met het gebruik van verschillende codelijsten voor Business/Life-events. Het Type attribuut bevat een Code, waarbij je kan definiëren dat elke entry van een zelf gemaakte "BusinessLifeEventCodeList" een Code is.

Hiermee bedoel ik dat het mogelijk is om bvb een code lijst "BusinessLifeEventsCodeList" aan te maken waarvan alle mogelijke waardes, bvb: `geboorte`, `huwen`, `overlijden`... als instantie van `Code` staan gespecifieerd. Dus: het is mogelijk om aparte codelijsten te hebben, een voor elke context.

> hoe dwing je bij de gebruiker af dat hij voor een LifeEvent geen BusinessEventType invult als alles door elkaar in één codelijst staat?

Momenteel wordt dit inderdaad niet afgedwongen. De enige manier om dit te doen is door een apart `type` attribuut te specifiëren voor `BusinessEvent` en `LifeEvent`, met in plaats van domein `Code` een `BusinessEventCode` respectievelijk `LifeEventCode`. Omdat het domein verschilt, zou je dus effectief 2 verschillende `type` attributen moeten hebben. Phil noemt een van deze in zijn antwoord `LifeEvent:Type`.

Hoewel dit steek houdt vanuit een business standpunt, is dit niet goed in de Linked Data wereld, wegens de punten die Phil aanhaalt.

> (Antwoord van Phil Archer)
> Sorry but I disagree. You can bet that if you have two similar properties, people will use them inconsistently. The combination of the subclass (LifeEvent) and the type carries all the necessary semantics to link to the correct code list. By introducing separate property types for the two classes, you facilitate the mistake of linking LifeEvent:Type to a business event that can't happen with just the type property.

Hiermee bedoelt hij dat het hebben van 2 afzonderlijke `type` attributen voor verwarring gaat zorgen bij gebruikers en zal leiden naar verkeerd gebruik. Het is daarom beter om 1 algemeen attribuut te hebben dat herbruikbaar is.
In praktijk zal uit de context moeten blijken welke code lijst bedoeld is (omdat je bvb weet dat je met een BusinessEvent werkt ipv een LifeEvent).

Persoonlijk volg ik Phil's argumentatie hier.

**Comment by GeertThijs** [comment]
Wat ik na overleg met @DieterDePaepe begrepen heb is dat het voordeel van de door mij voorgestelde aanpak niet opweegt tegen het nadeel dat ook Mr Archer schetst. En Dieter legde me ook uit dat je de codelijsten later nog kan specialiseren dmv mijn aanpak (met een type per subklasse) maar daarvoor hoeft de type bij de superklasse niet weg. In RDF schijnt zelfs een mechanisme te bestaan (subproperty genaamd) die toelaat om de type van de subklasse te substitueren door die van de superklasse (handig voor reasoners die de specialisatie niet kennen).
