### ISSUE TITLE
CPSV-AP: Event class not abstract in diagram.

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#21]
The Event class is said to be abstract in the specs but this isn’t visible in the diagram (class name should be in italic).

**Comment by GeertThijs** [comment]
Ik lees hier elders als commentaar dat in RDF een klasse niet abstract kan zijn. Oké, maar RDF is niet het de enig mogelijke doelsyntax van ons UML-model. En we willen wel degelijk communiceren dat deze klasse abstract is, zo staat het ook in de specs.

**Comment by DieterDePaepe** [comment]
Dit voorstel is aanwezig in het model dat aan de publieke werkgroepen is gepresenteerd.
