### ISSUE TITLE
CPSV-AP: Why limiting the possible types of an Agent?

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#22]
Why limiting the possible types of an Agent to Agent, Person and PublicOrganisation? Shouldn’t it be possible for a PublicService to refer to a non-PublicOrganisation (eg a contractor)? (See definition of PublicService: "mandatory or discretionary set of acts performed, or able to be performed, by **or on behalf** of a public organisation"). Shouldn’t all possible agenttypes be those mentioned in ORG, REGORG and CPOV (Agent, Organisation, Person, Group, FormalOrganisation, OrganisationalUnit, OrganisationalCollaboration, RegisteredOrganisation, PublicOrganisation)?

**Comment by DieterDePaepe** [comment]
[Link naar Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/why-limiting-possible-types-agent)

Misschien begrijp ik de vraag verkeerd, maar de service user/provider van een `PublicService` kan een `Agent` of gelijk welke subtype ervan zijn (`Group`, `Person`, `FormalOrganisation`,...).

**Comment by GeertThijs** [comment]
Ja, maar waarom heb je dan (optioneel weliswaar) nog de property type nodig? Blijkbaar om aan te geven wat het type is van de agent is die legal responsability heeft (zo zegt Mr Archer toch in zijn comment). Blijkbaar kan dat zijn: PublicOrganisations (logisch), maar ook Person and Agent (ttz een untyped Agent). (Vreemd trouwens: een persoon die legally responsable is voor een PublicService?) In het diagram is overigens helemaal geen HasLegalResponsability relatie te zien (HasCompetentAuthority lijkt er wat op maar gaat niet naar Agent maar naar PublicOrganisation.) Blijft verwarrend voor mij, die oplossing met Type.

**Comment by DieterDePaepe** [comment]
Wat Mr Archer bedoelt met "legal responsibility" is de `hasCompetentAuthority` relatie in het schema, die is beperkt tot publieke organisaties.

De service user/provider daarentegen kan gelijk welke Agent zijn (Person, Group, Organisation, PublicOrganisation, ...).

Het `type` dat in `Agent` staat is niet bedoeld om aan te geven of het om Group, Organisation... gaat. De precieze rol is mij echter ook niet duidelijk, ik had dit al verwoord in een [ander Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/cpsv-shouldnt-agent-be-abstract-entity).

**Comment by GeertThijs** [comment]
Hij zegt:

> The thinking here is that a Puiblic Service is something that is done from the public purse, usually as an obligation. Yes, the work may well be carried out by a contractor but the legal obligation is on the public organisation. Those contractors will be any subclass of Agent, so we're not restricting the kind of Agent that can play a role, just those that can have legal responsibility. 

Oké, ik wil gerust verstaan dat HasCompetentAuthority slaat op LegalResponsability. Maar HasCompetentAuthority is een relatie met PublicOrganisation, terwijl hij net argumenteert die Type property van Agent dient om aan te geven wie legal responsability heeft. Waarbij de mogelijke waarden vh type Agent, Person en Organisation zijn??? Sorry, ik volg niet meer.

**Comment by DieterDePaepe** [comment]
Discussie op JoinUp werd verschillend geïnterpreteerd door GeertThijs en Phil Archer. Er is geen geldig antwoord op gekomen.

Discussie wordt verdergezet in https://github.com/Informatievlaanderen/OSLO-Public-Discussion/issues/15
