### ISSUE TITLE
CPOV: Property CPOV:Temporal missing.

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#23]
A property CPOV:PublicOrganisation:Temporal comparable to CPSVAP: PublicService:Temporal or CPSVAP: PublicService:Channel:Availability should be added. Useful where the availability of the PublicService is not specific for the service but for the PublicOrganisation that provides it. Eg a PublicOrganisation has certain opening hours and the opening hours of its services derive from them. This saves needless copying of data from PublicOrganisation to PublicService. Adding weight to this issue is hat there is already a property CPOV:PublicOrganisation:Spatial, so why not a property CPOV:PublicOrganisation:Temporal.

**Comment by GeertThijs** [comment]
Iemand (@DieterDePaepe?) op WG Dienstverlening 3 van 7/11/2016 merkte denk ik terecht op dat een PublicOrganisation geen temporele Availability kan hebben, PublicOrganisation:Spatial slaat ook niet op de plaats waar de PublicOrganisation bereikbaar is maar op het gebied dat het bedient. Maw, de Channel:Avalability van de PublicOrganisation volstaat. Als iedereen dit volgt zal ik op JoinUp mezelf becommentariëren in die zin.

**Comment by DieterDePaepe** [comment]
[Link naar Joinup issue](https://joinup.ec.europa.eu/asset/cpov/issue/property-cpovtemporal-missing)

@GeertThijs Die opmerking kwam inderdaad van mij. Let op dat er momenteel ook geen `availability` gedefinieerd is op `PublicService`, wat misschien was wat je bedoelde? Maar daarvoor zou eerst #37 (of [Joinup](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/inconsistency-regarding-channel-hascontactpoint-and-hascost)) moeten opgelost raken.

**Comment by GeertThijs** [comment]
Intussen denk ik gewoon dat de term Availbility slecht gekozen is. Want ook Channels en Contactpoints zijn er in principe altijd tot ze worden afgeschaft. Misschien beter van OpeningHours tout court spreken? Mijn punt was gewoon dat als een PublicService geen specifieke openingsuren heeft, dan impliciet de openingsuren gelden van de PublicOrganisation. Of erger nog: die van Agent die de PublicService verstrekt.

**Comment by GeertThijs** [comment]
@DieterDePaepe: Inderdaad lijkt geen availability gedefinieerd op PublicService, maar als je er de uitleg bij de properties Spatial/Temporal op naleest (inderdaad 1 uitleg voor 2 properties) dan gaat het wel over Availability (in termen van openingsuren en dergelijke).

**Comment by GeertThijs** [comment]
Als je de uitleg leest bij PeriodOfTime in de specs kan je er zowel Availability als Openingsuren mee uitdrukken. Dus zowel sinds wanneer de PublicService al wordt aangeboden (door een startdatum te specifiëren), als in welke maanden vh jaar de dienst beschikbaar is (door gebruik van de ISO-notatie voor een periode binnen een jaar), als de openigsuren.

**Comment by DieterDePaepe** [comment]
`temporal` en `availability` stellen eigenlijk heel verschillende dingen voor, ook al lijkt het uit het schema dat ze hetzelfde voorstellen.

`temporal` is eigenlijk [dcterms:temporal](http://dublincore.org/documents/dcmi-terms/#terms-temporal): `Temporal characteristics of the resource.` En de definitie (die reeds vast ligt, aangezien het om een externe term gaat) zegt dat dit attribuut bepaalt wanneer de resource (de `PublicService`) bestaat. Dit heeft dus niet te maken met openingsuren volgens mij.

Zie ook de uitleg in sectie 3.12 van [de documentatie](https://joinup.ec.europa.eu/system/files/project/cc_di07171_cs270_d04.01_cpsv-ap-2.0_v1.05.pdf)
> The Period of Time class represents an interval of time. When linked from the Public Service to
the Period of Time (using Temporal, section Error! Reference source not found.) it defines
the period in which the service as a whole is available. This might just be a start date but with
no end date for services that are still active, or information about seasonal availability. An end
date will indicate the date on which the service was terminated.
If linked from a Channel (using the Availability property, section 3.11.6) then it indicates when
the particular channel is in operation. For example, the opening hours of an office or telephone
service

Ik weet niet welke vocabularium term ze voorstellen voor `availability`, dus het is moeilijk te zeggen of het hier enkel om openingsuren gaat of niet. De uitleg hierboven doet vermoeden van niet.

Over de vraag waar openingsuren bij horen: Ik vind dat er bij PublicOrganisation zeker geen openingsuren horen, want het gaat daar om `[...] a collection of people organized together into a community or other social, commercial or political structure.` Ook bij `PublicService` op zich niet. Bij `Channel` of `ContactPoint` (zoals [Phil voorstelt](https://joinup.ec.europa.eu/asset/cpov/issue/property-cpovtemporal-missing#comment-19024)).

> Als je de uitleg leest bij PeriodOfTime in de specs kan je er zowel Availability als Openingsuren mee uitdrukken. Dus zowel sinds wanneer de PublicService al wordt aangeboden (door een startdatum te specifiëren), als in welke maanden vh jaar de dienst beschikbaar is (door gebruik van de ISO-notatie voor een periode binnen een jaar), als de openigsuren.

Op welke text baseer je je? Je kan wellicht `PeriodOfTime` interpreteren als zijnde de openingsuren zelf, maar de aanwezigheid van het attribuut `OpeningHours` in het schema van `PeriodOfTime` lijkt dat tegen te spreken. Volgens mij staat dat attribuut daar sowieso verkeerd.

**Comment by GeertThijs** [comment]
Ik heb ook hierover nog eens overlegd met @DieterDePaepe. Ik wou vooral dat de openingsuren van de PublicOrganisation kon gebruikt worden indien er geen specifieke openingsuren voor de PublicService beschikbaar waren. Bv de PublicService ToelatingRommelmarktGent heeft geen eigen openingsuren, het zijn die vd PublicOrganisation die deze dienst verstrekt (Dienst MarktenEnForen van Stad Gent) die hier geldig zijn. Intussen hebben we begrepen dat zoiets als openingsuren thuishoort bij het Channel waarlangs je de dienst betrekt. Een Channel is een aparte entiteit en dus kunnen we er makkelijk eentje aanmaken (OwnedBy MarktenEnForen ih voorbeeld) die ook bruikbaar is voor de andere dientsen die door MarktenEnForen worden verstrekt. Dat betekent wel dat availability/temporal geen openingsuren meer mag bevatten. Ook mag een Channel geen PublicService specifieke properties meer bevatten, anders kan je de Channel niet voor meerdere PublicServices gebruiken. Intussen heeft Dieter vastgesteld dat Mr Archer het model al in die zin heeft aangepast, wat uiteraard toppie is!
