### ISSUE TITLE
CPOV: Temporal availability can vary with channel. 

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#24]
Moreover (continuing on issue "CPOV: Property CPOV:Temporal missing."): temporal availability can vary according through which channel the PublicOrganisation is contacted (eg from 8-19u by telephone, from 9-17u on-site). This is independent of the specific PublicServices that the PublicOrganisation provides.

**Comment by GeertThijs** [comment]
Waarmee ik wellicht wou suggereren: zet Channel ook maar als property bij PublicOrganisation. Komt omdat ik Channel niet als entity gemodelleerd had (intussen aangepast, zie comment bij #7). Als dit wel zo is kan je via de associatie PublicOrganisation-Channel temporele beschikbaarheid per kanaal definiëren. Ook deze los ik dus best op door mezelf te becommentariëren op Joinup.

**Comment by DieterDePaepe** [comment]
@GeertThijs: Ik snap het issue niet.

- Bedoel je CPSV?
- CPSV-AP definieert toch een "availability" op Channel?

**Comment by GeertThijs** [comment]
Ja, maar ik dacht er niet aan om de Channel-ownedBy-PublicOrganisation omgekeerd te doorlopen. Als je dat wel doet kan PublicOrganisation wel een kanaal (met een availability) hebben.

**Comment by DieterDePaepe** [comment]
[Link naar Joinup](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/cpov-temporal-availability-can-vary-channel)

Hangt er van af wat je wil bereiken en wat de uiteindelijke definitie van Channel zal worden (zie #37). Als je wil opgeven hoe je een organisatie moet bereiken, zullen er betere manieren zijn. Wellicht `org:siteOf` ofzo.

**Comment by GeertThijs** [comment]
Geen slecht idee, maar er is niet enkel de beschikbaarheid van de organisatie op een fysieke locatie. Bij het rommelmarkt voorbeeld kwam ik op specifieke uren waartussen je telefonisch contact kon nemen.

**Comment by DieterDePaepe** [comment]
Dan zou dit (gebaseerd op de termen die CPSV-AP gebruikt) een `schema:ContactPoint` zijn van de organisatie, met daarin het telefoonnummer en de openingsuren.

**Comment by DieterDePaepe** [comment]
Akkoord om dit issue te sluiten @GeertThijs ?

**Comment by GeertThijs** [comment]
Bij deze...
