### ISSUE TITLE
CPSV-AP: Offering a service vs executing a service

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#28]
Is the PublicService:ServiceUser relation (and Agent:Uses relation) suggests that CPSV-AP meant not only to exchange data on service offers (generic descriptions of services) but also on specific cases where a certain user x uses service y (actually an instantiation of the generic service)? Eg mister X applies for a driver's license (service Y being: IssueADriversLicence), the PublicOrganisation that offers the service opens a file and after some processing steps issues the license (during its lifetime the case has a status). The specs suggests something alike, definition of the relation PublicService:ServiceUser is "This property links a Public Service to an Agent who uses the service." and that of Agent:Uses is "This property links an Agent to a Public Service in which it plays the specific role of user, meaning that it provides the input and receives the output but does not play any direct role in providing the service. This will typically be an **individual citizen** or an outside organisation." If it is the intention to exchange also executions of the public service with CPSV-AP, then Status might be a missing property. Maybe there is a need for 2 views on PublicService in that case? Or for another application profile for service execution?

**Comment by woozong** [comment]
Dit is inderdaad de vraag waar ik gisteren mee zat.
Na de werkgroep had ik het gevoel dat we op dit moment het model beschrijven voor "offering a service". In dat geval is de "Agent who uses" gewoon een omschrijving van het doelpubliek van de dienstverlening. 
Voor "executing a service" mis ik wel meerdere dingen: status (en bijgevolg een soortement state-diagram), events specifiek voor verschillende stappen in de dienstverlening, etc... 
Willen we daar (het beschrijven van "executing a service") naartoe met OSLO ?
Of nog: wil OSLO enkel het "WAT" omschrijven, of ook het "HOE" ? (open vraag)

**Comment by DieterDePaepe** [comment]
Enkele definities uit [CPSV](https://joinup.ec.europa.eu/asset/core_public_service/description) die hiermee te maken hebben, er zijn verschillende definities in de RDF en PDF:

CPSV:uses (RDF)

> The uses property links an Agent to a Public Service in which it plays the specific role of user, meaning that it provides the input and receives the output but does not play any direct role in providing the service. This will typically be an individual citizen or an outside organisation.

CPSV:uses (PDF)

> Links an Agent to a Public Service in which it plays
the specific role of user, meaning that it provides the input and
receives the output but does not play any direct role in providing the
service. This will typically be an individual citizen or an outside
organisation.

CPSV:hasRole (RDF)

> This very general property links an Agent to a Public Service in which it plays some role. Both 'provides' and 'uses' are sub properties of playsRole with specific semantics.

CPSV:hasRole (PDF)

> This very general property links an Agent to a PublicService in which it plays some role. Its is a super property of both cpsv:provides and cpsv:uses.

CPSV:provides (PDF & RDF)

> Links an Agent to a Public Service for which it is
responsible. Whether it provides the service directly or outsources it
is not relevant, the Agent that provides the service is the one that
is ultimately responsible for its provision.

CPSV:PublicService (RDF & RDF)

> This class represents the service itself. A public service is the capacity to carry out a procedure and exists whether it is used or not. It is a set of deeds and acts performed by or on behalf of a public agency for the benefit of a citizen, a business or another public agency.

Extract uit PDF

> An individual service may be related to another in some way, in which case the two services
> can be linked using dcterms:related. If the relationship is such that one service requires
> another then the dcterms:requires relationship should be used. The dcterms:Agent
> class represents any individual, group or organisation that plays any role in the service. These
> include but are not limited to:
> • the public administration responsible for providing the service;
> • the public administration that defines the rules that regulate the service;
> • the organisation(s) that deliver the service on behalf of the responsible public body;
> • the public body responsible for passing the legislation or setting the policy or policies
> from which the rules are derived;
> • the person, organisation or group that uses the service.
> The basic roles are provides and uses and specific object properties are provided for these
> as shortcuts. However there are any number of roles that may be played in the provision or use
> of a service. Therefore a hasRole super property is provided.

Uit de definitie van PublicService ("the capacity to...") leid ik af dat het hier NIET om een dossier kan gaan. Ook conceptueel zijn een service en een dossier 2 verschillende dingen dus zou ik het een slechte beslissing van ISA vinden als zij deze samen nemen.

Ik denk dat de cpsv:uses relatie is bedoeld om aan te duiden dat een organisatie of persoon de service gebruikt, zonder specifieke details over status, opvolging, etc. Moest het gaan over een dossier zou de benaming "uses" ook vreemd zijn: gebruikt iemand een dossier?

**Comment by GeertThijs** [comment]
Goed geargumenteerd Dieter. Wellicht zal ISA het ook zo hebben bedoeld en is deze vraag overbodig. Dat betekent wel dat we (op termijn) een Package Dossier oid zullen moeten toevoegen. Waarbij je ook als nel zal zien denk ik dat de modellering grizelig dichtbij deze van Dienstverlening komt (heeft ook een Output, ook Evidence, een Agent speelt ook een Rol).

**Comment by woozong** [comment]
Omdat wij op dit moment "Dossier" modelleren, en dit inderdaad griezelig :-) veel op DienstVerlening lijkt, kwam bij mij de vraag op. Maar uit bovenstaande definities (thanks Dieter) blijkt inderdaad dat het hier (OSLO & CPSV) om DienstVerlening gaat. 
En een Dossier is inderdaad iets anders dan een DienstVerlening. 
Ik wil me dan ook nu al inschrijven op de toekomstige werkgroep "Dossier" ;)

**Comment by DieterDePaepe** [comment]
[Link naar Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/offering-service-vs-executing-service#comment-19023)

Uit de voorgestelde aanpassing van Phil Archer lijkt me nu dat ze Agent hier op een abstracte manier benaderen, bvb `SeniorCitizen` in plaats van `Jan Smith`. Indien dit zo is, gebruiken ze hier eigenlijk `Agent` als hoedanigheid, wat direct antwoord op een van de vragen van #11.

**Comment by GeertThijs** [comment]
De definitie van Person in FOAF is:

> Person class represents people. Something is a Person if it is a person. We don't nitpic about whether they're alive, dead, real, or imaginary. The Person class is a sub-class of the Agent class, since all people are considered 'agents' in FOAF.

Wat niet wijst op abstract gebruik. Trouwens onder abstract versta ik precies iets anders, nl het feit dat van een klasse geen instanties kunnen worden gemaakt, dit kan enkel van de subklassen van een klasse.
Ik zou eerder pleiten voor een property Doelpubliek voor PublicService, een property die ook in IPDC voorkomt.

**Comment by DieterDePaepe** [comment]
Abstract heeft inderdaad meerdere betekenissen (hoewel wel gerelateerd). Wat ik bedoelde was dat een `Person` als user van een `PublicService` niet een concreet iemand voorsteld (bvb Jan Smith), maar een abstracte rol kan voorstellen (bvb de sportsecretaris).

De relatie `uses` is effectief om doelpubliek uit te drukken volgens mij.

**Comment by GeertThijs** [comment]
Zoals daarnet besproken met @DieterDePaepe steun ik geen oplossing die de entiteit Persoon gebruikt als PersoonType bv om aan te geven wat het doelpubliek van een bepaalde service is. Zou immers betekenen dat we personen als Ouderling, ZwangereVrouw etc gaan aanmaken. Terwijl dit duidelijk geen instanties van Persoon zijn maar waarden vd codelijst Persoontype. Overigens: welk id zouden we geven aan een Persoon vh type Ouderling? Welke naam en voornaam? Ons voorstel is om de relatie Uses te schrappen en te vervangen door een property bij PublicService waarbij de waarde verwijst naar een codelijst PersonType of zoiets. Misschien moeten we Uses ook anders noemen, bv TargetAudiance. Ipv PersonType doen we misschien beter AgentType want het doelpubliek kan ook een Organization zijn.  @DieterDePaepe gaat deze comment nog op Joinup plaatsen (als dit al niet is gebeurd).

**Comment by DieterDePaepe** [comment]
Heb hier een specifieke issue over gemaakt: #38

**Comment by DieterDePaepe** [comment]
De gelinkte discussies hebben duidelijk gemaakt dat het altijd om het aanbieden van diensten gaat. De `uses` relatie zorgde voor verwarring, en is na onze feedback hierover bij ISA weggehaald.
