### ISSUE TITLE
CPSV-AP: Local version: vocabularium or application profile?

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#29]
Should we implement CPSV-AP locally (eg in Flanders) as a vocabularium or as an application profile? Or would it be a bad idea to downgrade (if you could use this term) a profile to a vocabularium? Practically this would mean the removal of the cardinalities and adding elements that where left out from used vocabularies. Motivation to do so would be that we would want to publish our local implementation together with a local implementation of CPOV which still remains a vocabularium. Or should we on the other hand develop a local profile for CPOV and leave CPSV-AP as it is? What is the best practice here? Are there any examples?

**Comment by DieterDePaepe** [comment]
[Link naar Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/local-version-vocabularium-or-application-profile)

Not sure I understand the issue. CPSV-AP does not define any terms, it only specifies mandatory/optional attributes and classes. So CPSV-AP cannot really be used a vocabulary.

I think the suggested practice is to follow CPSV-AP and add or define extra elements where needed for our use cases.

**Comment by GeertThijs** [comment]
Dit is een algemene vraag over onze werkwijze. OSLO is eigenlijk een domeinmodel, meer bepaald een conceptueel model voor het generieke domein. Maar daarbij inspireren we ons op INSPIRE (domeinmodel), ISA (vocabularia zoals CPOV, applicatieprofielen op vocabularia zoals CPSV-AP). Maar inspireren is nog iets anders dan implementeren of conformeren. Of gebeurt dat onrechtstreeks door de mapping of een conformance statement? En is ons domeinmodel dan na omzetting in RDF ook een vocabularium of een applicatieprofiel op bestaande vocabularia? En kan dat wel, je inspireren op een vocabularium of applicatieprofiel. Mogen we die toch ook wel beschouwen als een domeinmodel? Of is een vocabularium ruimer? Dit zijn echt vragen voor jou Dieter of voor iMinds in het algemeen.

**Comment by DieterDePaepe** [comment]
> Maar daarbij inspireren we ons op INSPIRE (domeinmodel), ISA (vocabularia zoals CPOV, applicatieprofielen op vocabularia zoals CPSV-AP). Maar inspireren is nog iets anders dan implementeren of conformeren.

Ik denk dat je niet een vocabularium kan implementeren of conformeren. Een vocabularium specificeert een lijst van termen met bijhorende definities die kunnen gebruikt worden. Een applicatie profiel daarentegen legt een structuur op, het bepaalt welke klassen en attributen moeten gebruikt worden. Als daaraan voldaan wordt, implementeer of conformeer je aan het profiel.

> Of gebeurt dat onrechtstreeks door de mapping of een conformance statement?

Verdergaand op de uitleg hierboven: Als wij dus een mapping maken waarbij ons domeinmodel in een vorm past die voldoet aan alle regels van het applicatie profiel, conformeren wij daaraan.

> En is ons domeinmodel dan na omzetting in RDF ook een vocabularium of een applicatieprofiel op bestaande vocabularia?

Het zal afhangen van hoe ons eindresultaat er uit zal zien, maar vermoedelijk gaan we beiden maken:

- Een vocabularium met daarin nieuwe termen + definities die wij nodig achten voor ons domeinmodel maar niet terugvinden in bestaande vocabularia.
- Een eigen set van regels, al dan niet een uitbreiding op de bestaande applicatie profielen, dat bepaalt welke klassen/attributen verplicht zijn bij uitwisseling van data tussen overheden onderling. Die regels zullen dan gaan over termen uit externe vocabularia en ons eigen OSLO vocabularium.

> En kan dat wel, je inspireren op een vocabularium of applicatieprofiel. Mogen we die toch ook wel beschouwen als een domeinmodel? Of is een vocabularium ruimer?

Zeker wel, want deze zijn tot stand gekomen op basis van use cases en/of domeinmodellen van anderen. Maar je mag een vocabularium niet zien als een opsomming van alles wat relevant is in een bepaald domein, je moet er in gaan "shoppen".

**Comment by GeertThijs** [comment]
Merci Dieter, dat is duidelijk! Ik concludeer dat we dus beginnen met een model met entiteiten, properties, associaties, definities etc. (vocabularium) waarop we daarna een profiel plaatsen door cardinaliteiten toe te voegen en evt minder belangrijke elementen weg te laten. Voor CPSV-AP is dat dan al gebeurd, voor ORGREGORGCPOV gaan we dat nog doen en voor het AdresModel kunnen we het nu al doen (is de facto al een profiel).
