### ISSUE TITLE
Beperkt OSLO zich tot publieke dienstverlening?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#3]
De [OSLO1 spec](https://www.v-ict-or.be/assets/5384d510ce3fb57c500006ad/OSLO1.1-specificaties.pdf) gebruikt volgende definities:

Sectie 2.2

> Het domein Dienstverlening omvat alle processen met een welgedefinieerde aanleiding en een
> welgedefinieerd resultaat, waarvan kwaliteit en doorlooptijd bewaakt moeten worden, bij een
> transactie tussen persoon en bestuur, tussen organisatie en bestuur en interbestuurlijk.

Sectie 2.6.1

> Het domein Dienstverlening omvat alle processen met een welgedefinieerde aanleiding en een
> welgedefinieerd resultaat, waarvan kwaliteit en doorlooptijd bewaakt moeten worden, bij een
> transactie tussen persoon en bestuur, tussen ‘organisatie en bestuur’ maar ook interbestuurlijk.

Bij [ISA CPSV](https://joinup.ec.europa.eu/asset/core_vocabularies/asset_release/core-vocabularies-v11#download) en CPSV-AP gebruikt men volgende definitie:

> A set of deeds and acts performed by or on behalf of a public agency for the benefit of a citizen, a business or another public agency.

Om compatibel te zijn met ISA zullen we OSLO ook moeten beperken tot publieke organisaties.

**Comment by dhaeneth** [comment]
Fout. Het gaat om diensten geleverd door of namens een publieke organisatie ten aanzien van burger, bedrijf of overheid.  'Beperken tot publieke organisaties' is te beperkend qua omschrijving voor wat voor ogen hebben. In tweede orde kijken we dan naar de definitie van 'publieke organisatie' als zijnde 'elke organisatie die binnen wet, decreet of regelgeving gedefinieerd wordt als zijnde publiek van aard'.

**Comment by GeertThijs** [comment]
@dhaeneth: Een misverstand denk ik. Ik was oorspronkelijk niet zeker of OSLO1 zich beperkte tot publieke dienstverlening, ik dacht dat het ook ging over dienstverlening rechtstreeks aangeboden aan de burger door niet-publieke organisaties of zelfs niet noodzakelijk in opdracht van een publieke organisatie. Maar als ik beide definities lees gaat het in beide gevallen toch wel over interactie van een burger of organisatie met een bestuur. Waarbij ISA iets ruimer is en zegt dat de interactie ook in opdracht ve bestuur kan gebeuren. Dus we moeten OSLO niet beperken, we moeten het zelfs uitbreiden.

**Comment by rafbuyle** [comment]
Idd. +1;

Van: GeertThijs [mailto:notifications@github.com]
Verzonden: zaterdag 29 oktober 2016 23:08
Aan: Informatievlaanderen/OSLO <OSLO@noreply.github.com>
Onderwerp: Re: [Informatievlaanderen/OSLO] Beperkt OSLO zich tot publieke dienstverlening? (#3)


@dhaeneth<https://github.com/dhaeneth>: Een misverstand denk ik. Ik was oorspronkelijk niet zeker of OSLO1 zich beperkte tot publieke dienstverlening, ik dacht dat het ook ging over dienstverlening rechtstreeks aangeboden aan de burger door niet-publieke organisaties of zelfs niet noodzakelijk in opdracht van een publieke organisatie. Maar als ik beide definities lees gaat het in beide gevallen toch wel over interactie van een burger of organisatie met een bestuur. Waarbij ISA iets ruimer is en zegt dat de interactie ook in opdracht ve bestuur kan gebeuren. Dus we moeten OSLO niet beperken, we moeten het zelfs uitbreiden.

**Comment by rafbuyle** [comment]
http://ec.europa.eu/newsroom/dae/document.cfm?doc_id=3179

… ICT-enabled collaborative service production refers to any public service that is electronically
provided by government, citizens, NGOs, private companies and individual civil servants, in
collaboration or not with government institutions, based on government or citizens-generated data
[17]. It leads to changing roles and relationships, where also the distinctions between professional,
politician, practitioner, civil servant, expert, consumer and citizen are blurring [10]. This may make
governments "invisible", where the boundaries between public and private services and between the
different actors are blurred and where public services are provided in alignment with existing
workflows and thereby reduce burden to a minimal level…

Van: Raf Buyle Namens raf.buyle@gmail.com
Verzonden: zaterdag 29 oktober 2016 23:25
Aan: 'Informatievlaanderen/OSLO' <reply@reply.github.com>; Informatievlaanderen/OSLO <OSLO@noreply.github.com>
Onderwerp: RE: [Informatievlaanderen/OSLO] Beperkt OSLO zich tot publieke dienstverlening? (#3)

Idd. +1;

Van: GeertThijs [mailto:notifications@github.com]
Verzonden: zaterdag 29 oktober 2016 23:08
Aan: Informatievlaanderen/OSLO <OSLO@noreply.github.com<mailto:OSLO@noreply.github.com>>
Onderwerp: Re: [Informatievlaanderen/OSLO] Beperkt OSLO zich tot publieke dienstverlening? (#3)


@dhaeneth<https://github.com/dhaeneth>: Een misverstand denk ik. Ik was oorspronkelijk niet zeker of OSLO1 zich beperkte tot publieke dienstverlening, ik dacht dat het ook ging over dienstverlening rechtstreeks aangeboden aan de burger door niet-publieke organisaties of zelfs niet noodzakelijk in opdracht van een publieke organisatie. Maar als ik beide definities lees gaat het in beide gevallen toch wel over interactie van een burger of organisatie met een bestuur. Waarbij ISA iets ruimer is en zegt dat de interactie ook in opdracht ve bestuur kan gebeuren. Dus we moeten OSLO niet beperken, we moeten het zelfs uitbreiden.

**Comment by GeertThijs** [comment]
@rafbuyle: Die definitie zegt inderdaad dat zowat iedereen de PubliekeDienst kan aanbieden. Als het erom gaat om precies te definiëren wat dan een PubliekeDienst is, verschuift CPSV-AP het probleem naar de PubliekeOrganisatie die de dienst aanbiedt of in wiens naam de dienst wordt aangeboden. Gelukkig is de definitie in CPOV dan weer wel duidelijk: "any organization that is defined as being part of the public sector by a legal framework at any level" en meer gedetailleerd "the State, regional or local authorities, bodies governed by public law and associations formed by one or several such authorities or one or several such bodies governed by public law" waarbij "governed by public law" uitgelegd wordt als volgt "“(a) established for the specific purpose of meeting needs in the general interest, not having an industrial or commercial character; and (b) having legal personality; and (c) financed, for the most part by the State, or regional or local authorities, or other bodies governed by public law; or subject to management supervision by those bodies; or having an administrative, managerial or supervisory board, more than half of whose members are appointed by the State, regional or local authorities or by other bodies governed by public law".

**Comment by dhaeneth** [comment]
@GeertThijs @rafbuyle Klopt - definitie is natuurlijk nog altijd zeer ruim, maar vormt de basis waarop heel wat zaken geënt worden (oa. bvb. opmaak van de Europese begroting via alle regionale overheden stoelt hierop).

Als ik verder denk .... : 
De definitie die we binnen OSLO gaan hanteren focust m.i. op dat publieke element (en onderscheidt het daarbij van de puur private dienstverlening). Dat 'publieke element' kunnen we terugvinden in 'Dienstverlening' (dienst/product wordt expliciet gedefinieerd in een regelgevend kader) of in 'Organisatie' (waarbij een Publieke Organisatie een dienstverlening aanbiedt - zelfs als die niet expliciet kadert in regelgeving).

Maw., om te weten of een dienst een PubliekeDienst is, moeten we kijken of deze het voorwerp is van een decreet of een besluit (regelgeving) of dat deze ingericht wordt door een PubliekeOrganisatie.

Let er hierbij wel op dat PubliekeOrganisatie stricto senso niet gelijk is aan 'Overheid'! Daaruit volgt dat PubliekeDienst geen synoniem is voor 'de catalogus van overheidsdienstverlening'. 

Binnen PubliekeDienst zullen we gaan moeten differentiëren en scopen (oa. ifv. de doelgroep, finaliteit, ...). Maar dat is dan 2e orde v/d definitie.

**Comment by DieterDePaepe** [comment]
We hebben dus een consensus dat de definitie van ISA voor PublicService volstaat voor OSLO lijkt mij.

Bronvraag van deze discussie lijkt mij afgehandeld: we beperken ons tot diensten die door of in opdracht van een publieke dienst worden uitgevoerd.

**Comment by dhaeneth** [comment]
Neen; door of in opdracht van een publieke organisatie :-)

**Comment by DieterDePaepe** [comment]
Conclusie: we beperken ons tot diensten die door of in opdracht van een publieke dienst worden uitgevoerd.
