### ISSUE TITLE
CPSVAP: PublicOrganisation is a subclass from Agent in CPSVAP, a subclass of Organisation in CPOV 

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#31]
In CPSVAP PublicOrganisation is a subclass of Agent, in CPOV it is a subclass of Organisation. OK, as Organisation is a subclass of Agent, PublicOrganisation is in fact also an Agent. In ORG an Organisation has Identifier, Purpose and Classification as possible properties. By deriving directly from Agent in CPSVAP PublicOrganisation has none of those. No problem however as in CPSVAP Identifier (and some other properties) where added to Agent. However: why not derive from Organisation in CPSVAP instead of from Agent to avoid confusion? See also the issue "CPSV:PublicOrganisation has 2 Identifiers" and the issue "CPSV:Shouldn't Agent be abstract?".

[Link to Joinup issue](https://joinup.ec.europa.eu/asset/cpsv-ap/issue/publicorganisation-subclass-agent-cpsvap-subclass-organisation-cpov)

**Comment by DieterDePaepe** [comment]
Het werd bevestigd dat het hier ging om een versimpelde voorstelling van het diagram.
