### ISSUE TITLE
OSLO: Historiek of niet?

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#32]
OSLO1 zegt historiek bewust buiten scope te hebben gehouden: "Historiek valt vandaag buiten scope van OSLO (temporele aspecten zijn bewust buiten de scope
gehouden), waar nodig is een geldigheidsperiode (van tot datumopgenomen).". Maar voegt uiteindelijk een geldigheidsperiode en een herkomst toe aan de meeste kernobjecten, maw zowel terreinhistoriek als databankhistoriek (of ValidTime en TransactionTime in databank termen). Enige objecten waar net geen ValidTime bijstaat zijn Dienstverlening en Product (Product:Geldigheidsduur is geen geldigheidsperiode, zie #13). Normaal gezien wordt in een vocabularium geen historiek voorzien en ook in het CPSV applicatieprofiel is het niet voorzien (hoewel er in de specs wel sprake van is bij Participation). Bij Persoon en Organisatie zijn er custom historiek properties (bv geboortedatum). Bij ORG zien we een periode vermeld voor de duur van een Membership. Maw: wanneer historiek werkelijk eigen is aan de entiteit dan duikt ze op, maar ze wordt niet systematisch ingevoerd zoals bij OSLO.

**Comment by DieterDePaepe** [comment]
Systemtime zal systematische (op alle entiteiten) voorzien door middel van een applicatie profiel, validtime zal niet systematisch voorzien worden op het vocabularium waar vereist.

Vb systemtime (wanneer iets in het systeem is geregistreerd): tijd van aanmaken sleutel.
Vb validtime (tijd van effectieve gebeurtenis): geboortedatum, lidmaatschap van x tot y....
