### ISSUE TITLE
CPOV: Herhaling van entiteiten uit ORG:Organisation bij CPOV:PublicOrganisation

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#33]
Sommige elementen van CPOV:PublicOrganisation zijn al aanwezig bij ORG:Organisation (ChangeEvent, OrganisationalUnit, purpose, classification etc). In se geen probleem, in specs CPOV staat dat ze in RDF gebonden zijn aan zelfde elementen in ORG. Alleen: hoe modelleren we dit in UML als bv ChangeEvent bij CPOV een extra property heeft (hasFormalFramework) die niet voorkomt bij ORG:Organisation:ChangeEvent.

**Comment by GeertThijs** [comment]
De dubbele elementen heb ik verwijderd uit het model (ttz OrganizationalUnit & ChangeEvent). Het feit dat ChangeEvent binnen de CPOV context een extra subklasse heeft heb ik opgelost door die subklasse in CPOV te laten staan maar te koppelen aan org:ChangeEvent. Analoog voor de extra relatie hasFormalFramework. Op beide relaties heb ik een constraint geplaatst (die in RDF echter verloren zal gaan vrees ik).

**Comment by GeertThijs** [comment]
Andere oplossing zou zijn om uit te breiden door subtyping. Maar een ChangeEvent in ORG is er nog altijd een in CPOV, alleen met wat meer properties. In RDF allemaal geen probleem blijkbaar, gewoon de nieuwe versie mappen op die van ORG, klopt dat? En is dat wat dan syntax-binding wordt genoemd? En mag je bij dit proces ook properties weglaten? Zie ook #34.

**Comment by DieterDePaepe** [comment]
Ik denk dat je 2 dingen aan het verwarren bent.

Een vocabularium als CPOV definieert een aantal termen. Bij deze definities kunnen ze voortbouwen op reeds bestaande vocabularia zoals ORG. Als concreet voorbeeld: CPOV definieert `FoundationEvent` als subklasse van `org:ChangeEvent`. Het feit dat ook `ChangeEvent` vermeld staat in de documentatie van CPOV komt gewoon omdat deze relevant is om de nieuwe termen uit CPOV te kaderen.

Een vocabularium definieert gewoon een aantal termen die kunnen gebruikt worden door mensen, zonder daarbij aan te raden welke termen moeten effectief gebruikt worden in applicaties of data uitwisseling. De enige coherentie tussen de termen uit een vocabularium is dat ze typisch in eenzelfde context relevant zijn.

Wanneer men effectief RDF data wil publiceren, moet men de keuze maken welke termen te gebruiken. Soms wordt hiervoor een applicatie profiel gemaakt, maar dat hoeft niet, men kan ook gaandeweg beslissen welke termen te gebruiken zonder dit ergens te documenteren. Bij deze keuze is men volledig vrij om te "shoppen" in gelijk welk vocabularium. Je spreekt dus niet echt van het weglaten van termen.

Terugkerend naar de originele vraag, ik denk dat je dit op 2 manieren kan voorstellen in UML.
- Je geeft elk element (relatie, attribuut, klassenaam) een kleur gebaseerd op het bron vocabularium.
- Je vermeld de namespace bij elk element. Bvb `org:ChangeEvent` ipv `ChangeEvent`

Maar is het effectief nodig dit onderscheid te kunnen zien in UML?
