### ISSUE TITLE
CPOV: FOAF:Agent & FOAF:Person uitgebreid in CPOV.

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#34]
Agent en Person in ORG zijn in feite FOAF:Agent en FOAF:Person maar worden in ORG (en ook elders) uitgebreid met specifieke properties. Wellicht een non-issue want een vocabularium mag naar believen toevoegen of weglaten uit het overgenomen vocabularium?

**Comment by bertvannuffelen** [comment]
Toevoegen is geen probleem.

Weglaten is mogelijks een issue.

Als ontology A een class CA definieerd met een verplicht veld description. Dan moet een ontology B die zegt dat een class CB een subclass is van CA ook verplicht het veld description voorzien.

**Comment by GeertThijs** [comment]
Ik dacht dat je naar believen kon shoppen bij het gebruik van een vocabularium? Ttz zowel toevoegen als weglaten? Dit klopt dus niet?

**Comment by GeertThijs** [comment]
Zie ook #15.

**Comment by DieterDePaepe** [comment]
Bert bedoelt hier met "ontology" wat wij een applicatie profiel noemen. Dus: iemand die een applicatie profiel volgt kan daar eigen termen extra bijvoegen en nog steeds compliant zijn, maar hij kan geen termen weglaten.

Originele issue is inderdaad een non-issue. Zie ook #33.
