### ISSUE TITLE
CPSV-AP: Dienst beschrijven vanuit welk standpunt?

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#35]
Bij het uitwerken vh voorbeeld vd Gentse Rommelmarkt heb ik de dienst beschreven vanuit het standpunt vd publieke organisatie (ttz de Stad Gent). Maw de dienst heet "ToelatingVerlenenVoorRommelmarktGent". Maar ik realiseer mij dat het misschien meer opportuun is om hem te beschrijven vanuit het standpunt van de gebruiker? Zou dan worden: "ToelatingVerkrijgenVoorRommelmarktGent". Wat doen we hiermee?

**Comment by GeraldineNolf** [comment]
@GeertThijs Correct: als we een dienst beschrijven vanuit de publieke organisatie, dan spreken we van metadata bij dat product (bv. een service). Dan spreken we over ISO/INSPIRE metadata of DCAT-AP om de beschrijving tegen in te vullen.
Echter gaat het hier om dienstverlening, wat echt vanuit de burger moet zijn. Hier spreken we van CPSV-AP. 
Ik denk dat dit de grote clou is in het onderscheid tussen de pure metadata (als beschrijving van data, diensten, documenten, ...) en de beschrijving van dienstverlening (een totaalpakketje voor een doelpubliek (waarbij gegevens of informatie wel input of output kan zijn)).

**Comment by GeertThijs** [comment]
Eigenlijk hebben we hier dus 2 applicatieprofielen:

- Standpunt PubliekeOrganisatie: Inventariseren van bestaande diensten (bv ten behoeve van stroomlijning, optimalisatie)
- Standpunt Burger: Opzoeken van de gewenste dienst

Hier zit zeker dezelfde info achter, alleen denk ik dat het eerste standpunt (PubliekeOrganisatie) meer diensten omvat, ook een aantal interne diensten die misscchien niet relevant zijn voor de burger maar wel voor andere diensten. Tenzij we Burger verbreden naar Gebruiker natuurlijk, alleen moeten we dan ergens toch Doelpubliek als property opnemen in CPSV-AP zodat desgewenst de interne diensten kunnen worden weggelaten. Misschien een ideetje om te posten bij CPSV-AP dat nog tot 9/11 in review is.

**Comment by GeertThijs** [comment]
@GeraldineNolf: Metadata beschrijft toch data, dus niet de producten zelf maar de dataproducten die ervan afgeleid zijn? Maar mijn kennis van metadata is sinds de tweede helft van de jaren 90 (toen ik heb meegewerkt aan de eertste metadatabank vh OC GIS-Vlaanderen) niet meer bijgewerkt natuurlijk :-)

**Comment by GeraldineNolf** [comment]
Je hebt gelijk @GeertThijs, het is kwestie van semantiek. 
Een product, hier in de semantische betekenis van de ISO-norm voor ProductSpecificaties. 
Kunnen data, diensten, documenten, applicaties, ... zijn. Dus idd niet van het gegeven als object op het terrein.
En voor elk van die soorten producten zal een beschrijving ervan nodig zijn. Die gebeurt idd via metadata (data over de data). Kan in verschillende standaarden gebeuren. Bv. ISO/INSPIRE voor "geografische gegevens", DCAT-AP voor "open data", EAD voor "documenten"... En dan CPSV-AP voor dienstverlening...?
En via die beschrijvingen, getoond in een catalogus, kan je op zoek naar producten. (Vergelijk met de Ikea-catalogus:je vindt er welke producten ze hebben, een titel, wat dat ding is, hoeveel het kost, door wie gemaakt, kwaliteit ervan, ...)
Basisprincipes voor data-leveranciers die op het veld zitten, met meerdere van die "productsoorten": keep-it-simple & once-only. 
Dus, waar overlap (bv. Geo en toch ook open data), moeten we met goede mappings, vereenvoudiging, linken, ... tot in de standaarden zelf proberen oplossingen te vinden om aan die principes te kunnen voldoen. (Je wil niet dat die gegevens dan 2x gemetadateerd moeten worden, 1x in ISO/INSPIRE en nog eens in DCAT-AP; neen, je wil dat dit maar 1x moet beschreven worden en dan automatisch doorstroomt in alle juiste catalogi, van de ene standaard in de andere, en zo op alle portalen verschijnt waar het hoort).
Metadata om onze informatiehuishouding op orde te zetten en krijgen. Vs dienstverlening naar je doelpubliek dat je wil bereiken. (Weet idd niet of dit altijd dé burger is, voor mij is dat niet zo.)

**Comment by GeertThijs** [comment]
@GeraldineNolf: ISO/INSPIRE metadatanorm om metadata van geografische data te beschrijven (data zoals de geografische extent om snel een dataset terug te vinden in een cataloog), DCAT-AP om metadata van open data te beschrijven (zodat je die snel kan terugvinden op het web), EAD om metadata van documenten te beschrijven (bv de naam van de auteur om snel bv de titels geschreven door dezelfde auteur terug te vinden in een cataloog). En CPSV-AP? Niet om de metadata van data over dienstverleningen te beschrijven toch? Maar om die publieke dienstverleningen en hun output (samen producten van de overheid) te beschrijven. Niet om snel een dataset terug te vinden mbt publieke dienstverlening maar om de dienstverlening zelf terug te vinden. Of ben ik aan het hallucineren?

**Comment by GeraldineNolf** [comment]
Helemaal correct Geert!

**Comment by GeertThijs** [comment]
Oké, zucht van verlichting. Overigens is er wel een bron voor al die verwarring. CPSV-AP profileert zich als een vocabularium en dus denkt iedereen aan RDF. En wat is RDF oorspronkelijk? Niet iets om dingen te beschrijven nee, iets om data over dingen in webpagina's te beschrijven. Metadata dus! Dat krijg je met het web dat oorspronkelijk niet zelf data was maar ernaar verwees maar nu juist door die annotaties en stuff zelf data wordt.

**Comment by GeertThijs** [comment]
Of nee: je bedoelt dat het correct is dat ik aan het hallucineren ben of wat?

**Comment by GeraldineNolf** [comment]
Nee, hoor, je bent correct. Niet aan het hallucineren! :)

**Comment by GeertThijs** [comment]
Intussen heb ik in IPDC en elders gezien hoe dit wordt opgelost: niet ToelatingVerkrijgenVoorRommelmarktGent of ToelatingVerlenenVoorRommelmarktGent, gewoon ToelatingRommelmarktGent. Of vinden jullie dat wanneer je van een Dienstverlening sprrekt dat er een werkwoord in de naam moet staan? Nu klinkt de naam van de Dienstverlening misschien teveel als de naam van de Output die ze aflevert.

**Comment by DieterDePaepe** [comment]
De identifier van een dienstverlening is op zich niet relevant, want dat zal een gebruiker niet te zien krijgen (hij zal de `name` en `description` van de dienstverlening zien). Natuurlijk is het wel handig om identifiers te gebruiken die ook kunnen geïnterpreteerd worden, ik zou opteren voor het kortste waarin alles gezegd is: `ToelatingRommelmarktGent`. Er is sowieso veel kans dat na verloop er verschillende naam-conventies zullen ontstaan.

Om terug te komen op het originele issue: ik zie geen nood om een onderscheid te maken tussen het standpunt van de gebruiker en het standpunt van interne werking, op het vlak van vocabularium termen. Qua applicatie profiel kan er inderdaad wel een verschil zijn, hiervoor hebben we use cases nodig.
