### ISSUE TITLE
Relatie Site-Gebouweenheid

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLO#36]
In OSLO1 koppelden we een Organisatie aan gebouweenheden ter substitutie vh Postadres, Leveringsadres etc. In ORG wordt een Organisation gekoppeld aan zijn Site's. Eerst dacht ik Site op Gebouweenheid te kunnen mappen, maar de definitie van Site is:

> An office or other premise at which the organization is located. Many organizations are spread across multiple sites and many sites will host multiple locations.

Aangezien Gebouweenheden dienst doen als locaties zou er een associatie tussen Site en Gebouweenheid moeten bijkomen. Waarbij een Site uit meerdere Gebouweenheden kan bestaan.

**Comment by DieterDePaepe** [comment]
Ik ga er van uit dat je `VerblijfsObject` (`OSLO:ResidenceObject`) bedoelt?

Ik zie op het eerste zicht geen conflict om `VerblijfsObject` te mappen op `Site`. Zie [de usage note](https://www.w3.org/TR/vocab-org/#class-site):

> In most cases a Site will be a physical location. However, we don't exclude the possibility of non-physical sites such as a virtual office with an associated post box and phone reception service. Extensions may provide sub-classes to denote particular types of site.

Via `locn:Location` en `locn:address` kunnen adressen gekoppeld worden.

**Comment by GeertThijs** [comment]
- Verblijfsobject is al enige tijd hernoemd naar Gebouweenheid.
- In de definitie die jij aanhaalt zie ik geen referentie naar iets als een Gebouweenheid.
- Een Site kan overigens uit meerdere gebouwen bestaan en dus meerdere gebouweenheden omvatten.

**Comment by DieterDePaepe** [comment]
- Ah, ik zou eens de geupdate versie moeten bekijken dus!
- Wat is onze definitie van gebouweenheid? Een losstaand gebouw?
- Ik vermoed dat onze gebouweenheid een specialisatie van `org:Site` zou kunnen zijn.

**Comment by GeertThijs** [comment]
Een gebouw is een functionele eenheid binnen een gebouw. Voorbeeld: appartement, winkel etc. Een alleenstaande woning krijgt ook een gebouweenheid.

**Comment by DieterDePaepe** [comment]
Een `Site` kan een filiaal, zetel, winkel... zijn en kan meerdere locaties bevatten. Een `Site` is dus wel effectief verschillend van een een `VerblijfsObject`/`AdresseerbaarObject`

Zie spec van [Site](https://www.w3.org/TR/vocab-org/#class-site):
> An office or other premise at which the organization is located. Many organizations are spread across multiple sites and many sites will host multiple locations.
> In most cases a Site will be a physical location. However, we don't exclude the possibility of non-physical sites such as a virtual office with an associated post box and phone reception service. Extensions may provide sub-classes to denote particular types of site.
