### ISSUE TITLE
Ontbrekende link Agent-Product bij OSLO1

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#4]
OSLO1 heeft geen link tussen OSLO1:Agent en OSLO1:Product (= Dienst) terwijl ISA dit wel heeft in CPSV en CPSV-AP.

**Comment by GeertThijs** [comment]
Deze issue vervalt als we terug de oorspronkelijke mapping OSLO:Dienstverlening op ISA:PublicService en OSLO:Product op ISA:Ouput aanhouden.
