### ISSUE TITLE
Overleden persoon, maar plaats en datum van overlijden niet gekend

### ISSUE THREAD

**Issue by jdevreese** [Informatievlaanderen/OSLO#45]
We moeten soms data uitwisselen die niet uit authentieke bronnen zoals het rijksregister afkomstig is. Die data kan dus onvolledig zijn.

Er zijn gevallen waar we weten dat een persoon overleden is, maar waar we niet beschikken over een plaats of datum van overlijden. Hoe kunnen we in het Oslo² model voor zo'n gevallen toch aangeven dat een persoon overleden is?

**Comment by DieterDePaepe** [comment]
Issue verhuist naar: https://github.com/Informatievlaanderen/OSLO-Public-Discussion/issues/10
