### ISSUE TITLE
Wordt UML correct gebruikt?

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#46]
Opmerking van Yvan S. op een fragment uit het interne verslag van Organisatie 3:

> Vraag WB: Klopt het dat er, op basis van het voorgestelde model, 3 soorten organisaties zijn?: Public organisation, registered organization en formal organization. 
> Antwoord TD: Ja, maar deze soorten zijn niet disjunct, een organisatie kan van meerdere soorten tegelijk zijn, waarbij de velden van die soorten dan samengevoegd worden zodat er maar één keer een beschrijving moet worden gemaakt.
> Antwoord GT: inderdaad niet disjoint, een geregistreerde organisatie kan ook een publieke organisatie zijn, etc…

**Opmerking:**
In dat geval klopt het model niet volgens de UML-standaard.
Mijn opmerking gaat niet over de inhoud, maar over de modellering. (Als je een standaard wil definiëren, moet je bestaande standaarden daarbij correct gebruiken, vind ik.) In dit geval kan je geen specialisatie gebruiken. Vervang de relaties door een associatie met als naam "is een" en een cardinaliteit van 1 op 0 of 1.

**Comment by GeertThijs** [comment]
Een subklasse is een "is een" relatie. Waarom zou specialisatie in dit geval niet mogen?

**Comment by DieterDePaepe** [comment]
Definitie uit de [2.5 UML specificatie](http://www.omg.org/spec/UML/2.5/) (p198):

> Specialization is, in contrast to subsetting, a relationship in the domain of intentional semantics, which is to say it characterizes the criteria whereby membership in the collection is defined, not by the membership. In the case of Associations, specialization means that a link classified by the specializing Association is also classified by the specialized Association. Semantically this implies that sets calculated by eliminating duplicates from the collections representing the ends of the specializing Association are subsets of the corresponding sets calculated by eliminating duplicates from collections representing the ends of the specialized Association; this fact of subsetting may or may not be explicitly declared in a model.

Verder wordt op pagina 197 een diagram getoond waarin een specialisatie meermaals voorkomt.

Bij de voorbeelden waarom men UML zou willen uitbreiden, wordt volgend voorbeeld gegeven: "Add Constraints that restrict the way UML’s constructs are used (such as disallowing multiple
inheritance)."
