### ISSUE TITLE
Ontbrekende link JuridischKader-Product bij OSLO1

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#5]
OSLO1 heeft geen link tussen OSLO1:JuridischKader en OSLO1:Product (= Dienst) terwijl ISA dit wel heeft in CPSV en CPSV-AP (CPSV:FormalFramework).

**Comment by dhaeneth** [comment]
Dan moeten we bekijken hoe we dit wel opnemen, want vanuit verschillende invalshoeken is hier wel behoefte aan.

**Comment by GeertThijs** [comment]
Zie #4: Deze issue vervalt als we terug de oorspronkelijke mapping OSLO:Dienstverlening op ISA:PublicService en OSLO:Product op ISA:Ouput aanhouden..
