### ISSUE TITLE
Nut van JuridischKader en Machtiging bij OSLO1:Dienstverlening

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#6]
Bij OSLO1 is er een link tussen OSLO1:Dientverlening (= Dossier/Case) en OSLO1:JuridischKader. Dit JuridischKader is verbonden met OSLO1:Machtiging.

OSLO 1.1:

> 2.6.3 Juridisch kader
> De machtigingen zijn afgeleid van het juridisch kader, i.e. een set van wetten, decreten en
> richtlijnen die een bepaalde dienstverlening of machtiging documenteren.
> Het juridisch kader dat hier bedoeld wordt, is specifiek in het kader van de machtigingen die
> gebruikt worden om rollen te typeren in het kader van een bepaalde dienstverlening.
> 
> 2.6.4 Machtiging
> Binnen dienstverlening zijn er vershillende actoren (natuurlijke persoon, ambtenaar,
> gemandateerde voor een onderneming) die een specifieke rol opnemen. In een aantal van deze
> ‘dienstverleningen’ moet deze rol afgetoetst worden met een formele lijst.
> ● een lokale ambtenaar die uitreksels uit het strafregister mag opvragen (rol behandelaar)
> ● een persoon die een mandaat heeft in een vennootschap (rol aanvrager)
> ● architect voor een bouwaanvraag (rol betrokkene)
> Binnen de dienstverlening wensen we te refereren naar een document of lijst die deze rol
> bekrachtigd. Deze lijsten kunnen lokale bronnen zijn of kruispuntdatabanken (typisch met een
> geldigheidsperiode).

Is er een nut van deze 2 termen op het niveau van een instantie van een dienst?
Is er een nut van machtiging in het algemeen?

**Comment by dhaeneth** [comment]
In het algemeen is er zeker een nut hiervoor. We willen weten wie er bevoegd is om een bepaalde dienstverlening aan te bieden of uit te voeren. Er zal evenzeer een nut zijn aan het concept 'Machtiging' ihkv. geïnstantieerde dienstverlening of bvb. het initiëren van een lopende dienstverlening of het opvragen van bepaalde informatie door een derde (die dan gemachtigd is).

**Comment by GeertThijs** [comment]
OSLO:JuridischKader hebben we al in OSLO en het mapt op CPSV:FormalFramework (wat iets ruimer lijkt zie #10). In OSLO staat Machtiging bij Rol (logisch, je hebt eventueel een machtiging nodig om een rol te vervullen), echter in CPSV-AP is Rol een onderdeel van Participation dat meerdere rollen kan omvatten (zie #30). Rol is in CPSV-AP echter niet verder uitgewerkt, het is gewoon een codelijst. Maken we er een samengesteld datatype van om er Machriging aan toe te voegen?

**Comment by DieterDePaepe** [comment]
Zie mijn [comment bij #30](https://github.com/Informatievlaanderen/OSLO/issues/30#issuecomment-259463325): als Machtiging relevant is, moeten we volgens mij eenduidig voor CPSV-AP:Participation gaan.

@GeertThijs gezien de richting van de relaties in CPSV-AP weet ik niet of je dit in een samengesteld datatype kan krijgen? Je hebt namelijk:

    Agent -> Participation <- PublicService

**Comment by DieterDePaepe** [comment]
Ik sluit deze issue wegens de verkeerde premise van hoe OSLO1 op CPSV-AP mapt. `Machtiging` is enkel van toepassing in het kader van individuele dienst dossiers, dus valt buiten scope.
