### ISSUE TITLE
CPSV: Bedoeling van Agent bij relatie "uses PublicService"

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO#8]
CPSV definieert een relatie `uses` tussen CPSV:Agent en CPSV:PublicService.

Stelt CPSV:Agent hier een concrete persoon voor (bvb: Jan Smit) en is dit dus een manier om toch personen aan dossiers te koppelen, of gaat het eerder om abstracte personen (bvb: een gepensioneerde) die diensten kunnen gebruiken.

Voorgestelde oplossing: navragen bij ISA.

**Comment by dhaeneth** [comment]
Hangt af van de toepassing. Op niveau Catalogus zal het eerder gaan naar abstracte personen; op niveau gepersonaliseerde dienstverlening (ander AP) gaan we waarschijnlijk meer naar individuen.

**Comment by GeertThijs** [comment]
Als het afhangt van de toepassing moeten ih vocabularium (waaruit in een later stadium toepassingsprofielen worden afgeleid) beide opties mogelijk zijn...

**Comment by GeertThijs** [comment]
Vraag is dan hoe je concreet een abstracte Persoon modelleert. Een Persoon is een Persoon en geen Persoontype. Hoedanigheid is iets anders en Group ook.

**Comment by GeertThijs** [comment]
Vraag is toch ook of die abstracte personen nodig zijn als je de diensten wil groeperen per LifeEvent/BusinessEvent ipv volgens doelpubliek. Je kan ook beiden doen maar ik zou ipv abstracte personen dan eerder een property Doelpubliek toevoegen aan CPSV-AP.

**Comment by GeertThijs** [comment]
Zie #28

**Comment by DieterDePaepe** [comment]
De `uses` relatie is na discussie op JoinUp weggelaten na onze feedback hierover.

https://joinup.ec.europa.eu/asset/cpsv-ap/issue/service-user-agent
